version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - vue

  django:
    build: backend
    command: python project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  vue:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

