version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - vue

  django:
    build:
      context: ./django
      dockerfile: ./Dockerfile
      ports:
        - "8000:8000"

  vue:
    build:
      context: ./vue
      dockerfile: ./Dockerfile
      ports:
        - "8080:8080"

