# Generated by Django 4.1.7 on 2023-02-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_number", models.SmallIntegerField()),
                ("flat_number", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_number", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="CarMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Entrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntranceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_car", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntranceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("is_cooperative_member", models.BooleanField(default=False)),
                (
                    "access_forbidden_since",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TgLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_link", models.CharField(max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.personalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=5)),
                ("full_name", models.CharField(max_length=100)),
                (
                    "KPP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="housing.kpp"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.personalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InOutHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_entrance", models.BooleanField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.car",
                    ),
                ),
                (
                    "entrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.entrance",
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.human",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.entrancerequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entrancerequest",
            name="human",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="housing.human",
            ),
        ),
        migrations.AddField(
            model_name="entrancerequest",
            name="request_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="housing.personalaccount",
            ),
        ),
        migrations.CreateModel(
            name="EntrancePrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveSmallIntegerField()),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.cartype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entrance",
            name="KPP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="housing.kpp"
            ),
        ),
        migrations.AddField(
            model_name="entrance",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="housing.entrancetype"
            ),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="housing.personalaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="car_mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="housing.carmark"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="housing.cartype",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="housing.personalaccount",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="housing.street"
            ),
        ),
    ]
