"""
Django settings for project project.

Generated by 'backend-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "backend-insecure-4l$^s@5zrccc*so_=*5*rxkn$oquo1ix*ft)p%8yu%o&9c$_##"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "backend.contrib.admin",
    "backend.contrib.auth",
    "backend.contrib.contenttypes",
    "backend.contrib.sessions",
    "backend.contrib.messages",
    "backend.contrib.staticfiles",
]

MIDDLEWARE = [
    "backend.middleware.security.SecurityMiddleware",
    "backend.contrib.sessions.middleware.SessionMiddleware",
    "backend.middleware.common.CommonMiddleware",
    "backend.middleware.csrf.CsrfViewMiddleware",
    "backend.contrib.auth.middleware.AuthenticationMiddleware",
    "backend.contrib.messages.middleware.MessageMiddleware",
    "backend.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "backend.template.backends.backend.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "backend.template.context_processors.debug",
                "backend.template.context_processors.request",
                "backend.contrib.auth.context_processors.auth",
                "backend.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "backend.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "backend.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "backend.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "backend.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "backend.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "backend.db.models.BigAutoField"
